# Tiền xử lí data từ drugbank

In [1]:
import pandas as pd
import sqlite3
df = pd.read_csv("../data/raw_data/clean_drug_interactions_with_food.csv")
conn = sqlite3.connect("../data/database/drug-food-interaction.db")

In [2]:
df.head(10)

,drug_name,source,description,food_name
0,Lepirudin,"Knox C, Wilson M, Klinger CM, et al. DrugBank ...",Avoid herbs and supplements with anticoagulant...,garlic; ginger; ginkgo biloba; ginseng; chamomile
1,Bivalirudin,"Knox C, Wilson M, Klinger CM, et al. DrugBank ...",Avoid echinacea.,echinacea
2,Bivalirudin,"Knox C, Wilson M, Klinger CM, et al. DrugBank ...",Avoid herbs and supplements with anticoagulant...,ginkgo biloba; garlic; ginger; bilberry; dansh...
3,Peginterferon alfa-2a,"Knox C, Wilson M, Klinger CM, et al. DrugBank ...",Drink plenty of fluids.,fluids
4,Alteplase,"Knox C, Wilson M, Klinger CM, et al. DrugBank ...",Avoid herbs and supplements with anticoagulant...,ginkgo biloba; garlic; ginger; bilberry; dansh...
5,Interferon alfa-n1,"Knox C, Wilson M, Klinger CM, et al. DrugBank ...",Avoid alcohol.,alcohol
6,Darbepoetin alfa,"Knox C, Wilson M, Klinger CM, et al. DrugBank ...",Administer iron supplement. When initiating an...,iron supplement
7,Urokinase,"Knox C, Wilson M, Klinger CM, et al. DrugBank ...",Avoid herbs and supplements with anticoagulant...,ginkgo biloba; garlic; ginger; bilberry; dansh...
8,Reteplase,"Knox C, Wilson M, Klinger CM, et al. DrugBank ...",Avoid herbs and supplements with anticoagulant...,ginkgo biloba; garlic; ginger; bilberry; dansh...
9,Erythropoietin,"Knox C, Wilson M, Klinger CM, et al. DrugBank ...",Administer iron supplement. When initiating an...,iron supplement

In [4]:
def clean_text(text):
    text = str(text).lower().strip()
    return text

df["drug_name"] = df["drug_name"].apply(clean_text)
df["food_name"] = df["food_name"].apply(clean_text)

# description,source chỉ cần bỏ khoảng trắng 
df["description"] = df["description"].apply(lambda x: str(x).strip()) 
df["source"] = df["source"].apply(lambda x: str(x).strip())

df.head()

,drug_name,source,description,food_name
0,lepirudin,"Knox C, Wilson M, Klinger CM, et al. DrugBank ...",Avoid herbs and supplements with anticoagulant...,garlic
0,lepirudin,"Knox C, Wilson M, Klinger CM, et al. DrugBank ...",Avoid herbs and supplements with anticoagulant...,ginger
0,lepirudin,"Knox C, Wilson M, Klinger CM, et al. DrugBank ...",Avoid herbs and supplements with anticoagulant...,ginkgo biloba
0,lepirudin,"Knox C, Wilson M, Klinger CM, et al. DrugBank ...",Avoid herbs and supplements with anticoagulant...,ginseng
0,lepirudin,"Knox C, Wilson M, Klinger CM, et al. DrugBank ...",Avoid herbs and supplements with anticoagulant...,chamomile

In [5]:
# tách food_name về dạng chuẩn (unique)

df["food_name"] = df["food_name"].str.split(";")

df = df.explode("food_name")

df["food_name"] = df["food_name"].str.strip()
df.head()

,drug_name,source,description,food_name
0,lepirudin,"Knox C, Wilson M, Klinger CM, et al. DrugBank ...",Avoid herbs and supplements with anticoagulant...,garlic
0,lepirudin,"Knox C, Wilson M, Klinger CM, et al. DrugBank ...",Avoid herbs and supplements with anticoagulant...,ginger
0,lepirudin,"Knox C, Wilson M, Klinger CM, et al. DrugBank ...",Avoid herbs and supplements with anticoagulant...,ginkgo biloba
0,lepirudin,"Knox C, Wilson M, Klinger CM, et al. DrugBank ...",Avoid herbs and supplements with anticoagulant...,ginseng
0,lepirudin,"Knox C, Wilson M, Klinger CM, et al. DrugBank ...",Avoid herbs and supplements with anticoagulant...,chamomile

In [7]:
df.to_csv("../data/clean_data/clean_drugbank_data.csv",index=False)